name = "advanced-physics-thumbnailer"
main = "worker.mjs"
compatibility_date = "2026-03-15"
workers_dev = true

assets = { directory = "./assets", binding = "ASSETS" }

[vars]
FALLBACK_COURSE_NAME = "Modern physics"
ALLOWED_ORIGIN = ""
FRONTEND_FALLBACK_URL = ""
